#cloud-config
package_update: true
packages:
  - curl
  - iptables

runcmd:
  # Instala Tailscale
  - curl -fsSL https://tailscale.com/install.sh | sh

  # Habilitar reenvío de paquetes (IPv4/IPv6)
  - sysctl -w net.ipv4.ip_forward=1
  - sysctl -w net.ipv6.conf.all.forwarding=1
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
  - sysctl -p

  # Iniciar Tailscale y anunciar TODA la VNet
  - tailscale up --authkey tskey-auth-kGKKkPR9fH11CNTRL-zAGcoNfHHe211MPYDA7Ae2wHcvtR8JQGi  --advertise-routes=10.10.0.0/16 --accept-dns=false

  # Configurar NAT para que Tailscale pueda enrutar hacia la VNet
  - iptables -t nat -A POSTROUTING -s 100.64.0.0/10 -o eth0 -j MASQUERADE
  - netfilter-persistent save || true
  - netfilter-persistent reload || true